### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#457]
- [x] When selecting Launchpad UI is breaking

![Screenshot 2022-02-21 at 3 45 46 PM](https://user-images.githubusercontent.com/55599878/154935017-599387a4-b704-47da-9222-4283efa1a016.png)

- [x] Icons are wrongly aligned and Improve them

![Screenshot 2022-02-21 at 3 38 31 PM](https://user-images.githubusercontent.com/55599878/154934574-ab347db0-019e-4f73-bbbb-5934369b199a.png)

- [x] Link icon wrongly aligned

![Screenshot 2022-02-21 at 3 43 48 PM](https://user-images.githubusercontent.com/55599878/154934697-9dffc1b9-295a-4646-844f-fab76060177b.png)

- [x] Items are not aligned

![Screenshot 2022-02-21 at 3 47 57 PM](https://user-images.githubusercontent.com/55599878/154935352-4fc3cc93-7cb4-4677-bdb6-7db356d64c72.png)

- [x] Too much cluttery, we can give some padding b/w the two item

![Screenshot 2022-02-21 at 3 48 51 PM](https://user-images.githubusercontent.com/55599878/154935496-fdf47663-a90b-4b3a-bdbe-815dc2236e71.png)

- [x] Icon and Nav item are not aligned properly

![Screenshot 2022-02-21 at 3 52 24 PM](https://user-images.githubusercontent.com/55599878/154936087-692f6ee2-b2d8-435b-a746-629bb1779027.png)

**Comment by abhisheknaiidu** [comment]
@bigint i want to fix all of these issues 🙇🏽

**Comment by josealonso** [comment]
Sorry to ask, @abhisheknaiidu. I think you fixed some of those issues here https://github.com/Ricochet-Exchange/ricochet-frontend/issues/436. What happened then ?

**Comment by josealonso** [comment]
I think these issues have been resolved already. Let me know if this can be closed, @abhisheknaiidu, @bigint

**Comment by abhisheknaiidu** [comment]
@josealonso I can still see all the issues, will fix these by today!
